version: "3.1"

services:
  web:
    build: .
    container_name: odoo17-web
    ports:
      - "8069:8069"
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
      - PORT=5432
    depends_on:
      - db
    volumes:
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:15
    container_name: odoo17-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: